### ISSUE TITLE
Ad-supported version

### ISSUE THREAD

**Issue by deviantsemicolon** [Jaculabilis/nixpkgs-gold#3]
This would make you, the developer, a lot more money than just with a paid version

Even better, the ad-supported version could also require a subscription, which would dramatically increase profits.

**Comment by Jaculabilis** [comment]
Running ads in unlicensed builds instead of making a license a hard requirement was mentioned in #1, which I will probably implement soon. Making the license require a subscription just makes sense, though -- obviously nixpkgs gold :tm: requires only the highest standards of ongoing support, and in this economy it's widely agreed that subscription models are the best way to match COGS to customer usage.

**Comment by Jaculabilis** [comment]
This is now complete in #4.

**Comment by deviantsemicolon** [comment]
Congratulations on making such a wise business decision 🥂
